// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRXTkMAfWLnw_TvzTFoXADB7x3xr7Gdnc',
    appId: '1:126854682947:web:02e50e7539045e2fe8f7f6',
    messagingSenderId: '126854682947',
    projectId: 'eat-rem',
    authDomain: 'eat-rem.firebaseapp.com',
    storageBucket: 'eat-rem.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbE7QNUBx5e1-ZdNeGzb6mumhbNNCFe9k',
    appId: '1:126854682947:android:5ae066ad36c53539e8f7f6',
    messagingSenderId: '126854682947',
    projectId: 'eat-rem',
    storageBucket: 'eat-rem.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjMSk0al2ynYkiZxGO0nlGu283JJhzQ_Q',
    appId: '1:126854682947:ios:7fbe9fff9669fe97e8f7f6',
    messagingSenderId: '126854682947',
    projectId: 'eat-rem',
    storageBucket: 'eat-rem.firebasestorage.app',
    iosBundleId: 'com.example.netflixApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjMSk0al2ynYkiZxGO0nlGu283JJhzQ_Q',
    appId: '1:126854682947:ios:7fbe9fff9669fe97e8f7f6',
    messagingSenderId: '126854682947',
    projectId: 'eat-rem',
    storageBucket: 'eat-rem.firebasestorage.app',
    iosBundleId: 'com.example.netflixApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRXTkMAfWLnw_TvzTFoXADB7x3xr7Gdnc',
    appId: '1:126854682947:web:249641b3b59721c9e8f7f6',
    messagingSenderId: '126854682947',
    projectId: 'eat-rem',
    authDomain: 'eat-rem.firebaseapp.com',
    storageBucket: 'eat-rem.firebasestorage.app',
  );

}